discern_source_repo: git@github.com:edx/discern.git
ease_source_repo: git@github.com:edx/ease.git
# discern_dir: $app_base_dir/discern
# ease_dir: $app_base_dir/ease
discern_dir: /vagrant
ease_dir: /vagrant/ease
discern_settings: discern.settings
nltk_data_dir: /usr/share/nltk_data
remote_user: vagrant
discern_branch: dev
ease_branch: master
nginx_listen_port: 80
gunicorn_port: 7999
discern_user: vagrant
site_name: discern%